# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-application-config
  namespace: application
data:
  application.properties: |
    server.port=8080
    logging.level.root=INFO
    spring.datasource.url=${JDBC_URL}
    spring.datasource.username=${DB_USERNAME}
    # Other application properties
