# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: java-application
    spec:
      containers:
      - name: java-application
        image: IMAGE_NAME_PLACEHOLDER
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: java-application-config
              key: jdbc.url
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: java-application-config
              key: db.username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: java-application-secrets
              key: db-password
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
      volumes:
      - name: config-volume
        configMap:
          name: java-application-config
      - name: logs-volume
        emptyDir: {}
