name: Test OKE Connectivity via Bastion

on:
  workflow_dispatch:

jobs:
  bastion-connectivity:
    runs-on: ubuntu-24.04

    env:
      BASTION_OCID: ${{ secrets.BASTION_OCID }}
      OKE_NODE_OCID: ${{ secrets.OKE_NODE_OCID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up OCI CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip python3-pip
        pip3 install oci-cli

    - name: Configure OCI CLI credentials
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_CONFIG_FILE }}" > ~/.oci/config
        echo "${{ secrets.OCI_API_KEY }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/config
        echo "OCI CLI configured successfully"

    - name: Check if secrets are available
      run: |
        if [[ -z "$BASTION_OCID" || -z "$OKE_NODE_OCID" ]]; then
          echo "ERROR: Missing environment variables."
          exit 1
        fi
        echo "Secrets look good. Proceeding..."

    - name: Generate temporary SSH keypair
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 2048 -N "" -f ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create port-forwarding session via OCI Bastion
      id: port-forward
      run: |
        SESSION_OCID=$(oci bastion session create-port-forwarding \
          --bastion-id "$BASTION_OCID" \
          --target-resource-id "$OKE_NODE_OCID" \
          --target-port 22 \
          --ssh-public-key-file ~/.ssh/id_rsa.pub \
          --wait-for-state SUCCEEDED \
          --query "data.id" \
          --raw-output)
          --debug

        echo "SESSION_OCID=$SES_
