name: Connect to OKE via OCI Bastion

on:
  workflow_dispatch:

jobs:
  bastion-oke-connect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Set up SSH private and public keys
      run: |
        mkdir -p ~/.ssh
        echo "$BASTION_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      env:
        BASTION_SSH_PRIVATE_KEY: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}

    - name: Set up OCI config and key
      run: |
        mkdir -p ~/.oci
        # Patch the config to use the correct key path in the runner environment
        echo "$OCI_CONFIG" | sed 's|key_file=.*|key_file=~/.oci/oci_api_key.pem|' > ~/.oci/config
        echo "$OCI_PRIVATE_KEY" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem
      env:
        OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
        OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}

    - name: Start OCI Bastion Port Forward Session
      id: bastion
      run: |
       SESSION_OCID=$(oci bastion session create-port-forwarding \
       --bastion-id "$BASTION_OCID" \
       --target-resource-id "$OKE_NODE_OCID" \
       --target-resource-port 22 \
       --key-type "PUB" \
       --ssh-public-key-content "$(cat ~/.ssh/id_rsa.pub)" \
       --wait-for-state SUCCEEDED \
       --query 'data.id' --raw-output)
        echo "session_id=$SESSION_OCID" >> "$GITHUB_OUTPUT"
    env:
     BASTION_OCID: ${{ secrets.BASTION_HOST }}
     OKE_NODE_OCID: ${{ secrets.OKE_IP_ADDRESS }}
