  
name: Kubernetes lint manifests

on:
  push:
    branches:
      - "master"

  check_suite:
    types:
      - completed
jobs:
  lint_k8s:
    runs-on: ubuntu-24.04
    environment: nonprod
    name: Lint k8s, kubescore tests, kubeval tests on PR  Workflow
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

# Check if kubeseal, kubeval, gomplate, kube-score, oci present in worker cache
      - name: kubeseal, kubeval, gomplate, kube-score, oci cache
        id: kubeseal-kubeval-gomplate-kubescore-oci-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/bin/kubeseal
            ~/bin/kubeval
            ~/bin/gomplate
            ~/bin/kube-score
            ~/lib/oracle-cli
            ~/bin/oci
          key: kubeseal-kubeval-gomplate-kubescore-oci-cache-key

## kubeseal, kubeval, gomplate, kube-score, oci installation
#  Install kubeseal if was not found in cache
      - name: install kubeseal, kubeval, gomplate, kube-score, oci
        if: steps.kubeseal-kubeval-gomplate-kubescore-oci-cache.outputs.cache-hit != 'true'
        working-directory: .github/workflows
        env:
          ENV_INSTALL_KUBESEAL: true
          ENV_INSTALL_KUBEVAL: true
          ENV_INSTALL_GOMPLATE: true
          ENV_INSTALL_KUBESCORE: true
          ENV_INSTALL_OCI: true
        run: |
          ./install-dependencies.sh
      - name: Lint k8s, kubescore tests, kubeval tests, Yaml validations on PR
        run: |
          ENV_VALIDATE_SEALED_SECRETS_ENABLED=false ENV_VALIDATE_YAML_FILE_REFERENCES_IN_KUSTOMIZATION=true ./.github/workflows/lint-k8s-manifests.sh        
      - name: k8s secrets validation non prod
        env:
          BASTION_KEY: ${{ secrets.BASTION_KEY }}
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_KEY: ${{ secrets.OCI_KEY }}
          BASTION_IP_ADDRESS: ${{ secrets.BASTION_IP_ADDRESS }}
          OKE_IP_ADDRESS: ${{ secrets.OKE_IP_ADDRESS }}
        run: |
          ## Installation of binaries, set up .ssh and .kube dir
          mkdir -p ~/.oci/ ~/.ssh/ ~/.kube/
          echo "$OCI_CONFIG" > ~/.oci/config
          echo "$OCI_KEY" > ~/.oci/key
          echo "$BASTION_KEY" > ~/.ssh/bastion
          echo "$KUBECONFIG_FILE" > ~/.kube/config
          chmod 400 ~/.oci/key ~/.oci/config ~/.ssh/bastion
          - name: Debug bastion connectivity
        run: |
         ping -c 4 ${{ secrets.BASTION_IP_ADDRESS }} || true
         nc -zv ${{ secrets.BASTION_IP_ADDRESS }} 22 || true
          # Debug SSH connection
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/bastion opc@${{ secrets.BASTION_KEY }} exit
          ssh -o LogLevel=ERROR -o StrictHostKeyChecking=no -f -n opc@${{ secrets.BASTION_IP_ADDRESS }} -i ~/.ssh/bastion -N -L 6443:${{ secrets.OKE_IP_ADDRESS }}:6443 sleep 900
          ENV_ENABLE_BUILD_TEST=false ENV_VALIDATE_SEALED_SECRETS_ENABLED=true ./.github/workflows/lint-k8s-manifests.sh
    
