name: connection test oke

on:
  push:
    branches:
      - "master"

jobs:
  lint_k8s:
    runs-on: ubuntu-24.04
    environment: nonprod
    name: Connection test to OKE from GitHub Actions

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Check if required binaries are cached
      - name: kubeseal, kubeval, gomplate, kube-score, oci cache
        id: kubeseal-kubeval-gomplate-kubescore-oci-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/bin/kubeseal
            ~/bin/kubeval
            ~/bin/gomplate
            ~/bin/kube-score
            ~/lib/oracle-cli
            ~/bin/oci
          key: kubeseal-kubeval-gomplate-kubescore-oci-cache-key

      # Install binaries if not found in cache
      - name: Install kubeseal, kubeval, gomplate, kube-score, oci
        if: steps.kubeseal-kubeval-gomplate-kubescore-oci-cache.outputs.cache-hit != 'true'
        working-directory: .github/workflows
        env:
          ENV_INSTALL_KUBESEAL: true
          ENV_INSTALL_KUBEVAL: true
          ENV_INSTALL_GOMPLATE: true
          ENV_INSTALL_KUBESCORE: true
          ENV_INSTALL_OCI: true
        run: |
          chmod +x install-dependencies.sh
          ./install-dependencies.sh

      # Configure secrets and test Bastion/OKE connectivity
      - name: k8s secrets validation non prod
        env:
          BASTION_KEY: ${{ secrets.BASTION_KEY }}
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_KEY: ${{ secrets.OCI_KEY }}
          BASTION_IP_ADDRESS: ${{ secrets.BASTION_IP_ADDRESS }}
          OKE_IP_ADDRESS: ${{ secrets.OKE_IP_ADDRESS }}
        run: |
          # Setup OCI config and SSH
          mkdir -p ~/.oci/ ~/.ssh/ ~/.kube/
          echo "$OCI_CONFIG" > ~/.oci/config
          echo "$OCI_KEY" > ~/.oci/key
          echo "$BASTION_KEY" > ~/.ssh/bastion
          echo "$KUBECONFIG_FILE" > ~/.kube/config
          chmod 400 ~/.oci/key ~/.oci/config ~/.ssh/bastion

          # Start SSH tunnel to OKE
          ssh -o LogLevel=ERROR -o StrictHostKeyChecking=no -f -n \
            -i ~/.ssh/bastion \
            opc@${BASTION_IP_ADDRESS} \
            -N -L 6443:${OKE_IP_ADDRESS}:6443 sleep 900

      - name: Debug bastion connectivity
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/bastion opc@${{ secrets.BASTION_IP_ADDRESS }} exit
