name: Test OKE Connectivity via Bastion

on:
  workflow_dispatch:

jobs:
  test-oke-connectivity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}
        known_hosts: '[]'  # disable host verification; we'll manually add later
        name: id_rsa
        if_key_exists: fail

    - name: Add bastion host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

    - name: Test OKE connectivity via Bastion
      env:
        BASTION_USER: ${{ secrets.BASTION_USER }}
        BASTION_HOST: ${{ secrets.BASTION_HOST }}
        OKE_NODE_USER: ${{ secrets.OKE_NODE_USER }}
        OKE_NODE_IP: ${{ secrets.OKE_NODE_IP }}
      run: |
        echo "Testing SSH connectivity to OKE node via bastion..."
        ssh -o StrictHostKeyChecking=yes \
            -J "$BASTION_USER@$BASTION_HOST" \
            "$OKE_NODE_USER@$OKE_NODE_IP" \
            "echo ✅ Connected to OKE node successfully"
