name: Test OKE Connectivity via Bastion

on:
  workflow_dispatch:

jobs:
  test-oke-connectivity:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Test OKE Connectivity via Bastion
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          BASTION_USER: ${{ secrets.BASTION_USER }}
          BASTION_KEY: ${{ secrets.BASTION_KEY }}
          OKE_INTERNAL_IP: ${{ secrets.OKE_INTERNAL_IP }}
        run: |
          # Write private key to a file
          echo "$BASTION_KEY" > bastion.key
          chmod 600 bastion.key

          # Test SSH to OKE via Bastion
          ssh -o StrictHostKeyChecking=no \
              -i bastion.key \
              -J "${BASTION_USER}@${BASTION_HOST}" \
              "${BASTION_USER}@${OKE_INTERNAL_IP}" \
              "echo 'OKE connectivity test successful!'"
