name: Test OKE Connectivity via Bastion

on:
  workflow_dispatch:

jobs:
  test-oke-connectivity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.BASTION_HOST }}
        name: id_rsa
        if_key_exists: fail

    - name: Debug secret values (Optional)
      run: |
        echo "BASTION_USER=${{ secrets.BASTION_USER }}"
        echo "BASTION_HOST=${{ secrets.BASTION_HOST }}"
        echo "OKE_NODE_USER=${{ secrets.OKE_NODE_USER }}"
        echo "OKE_NODE_IP=${{ secrets.OKE_NODE_IP }}"
      # Remove or mask this step if secrets should not be displayed

    - name: Test OKE connectivity via bastion
      run: |
        echo "Testing SSH connectivity to OKE node via bastion..."
        ssh -o StrictHostKeyChecking=no \
            -J "${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}" \
