name: Test OKE Connectivity via Bastion

on:
  workflow_dispatch:

jobs:
  test-oke-connectivity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.BASTION_HOSTS }}

    - name: Test OKE connectivity via bastion
      run: |
        # Test basic SSH connectivity to bastion
        ssh -o StrictHostKeyChecking=no \
            -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} \
            ${{ secrets.OKE_NODE_USER }}@${{ secrets.OKE_NODE_IP }} \
            "echo 'Successfully connected to OKE node via bastion'"
        
        # Test kubectl connectivity via bastion (if configured)
        ssh -o StrictHostKeyChecking=no \
            ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} \
            "kubectl --kubeconfig ${{ secrets.KUBECONFIG_PATH }} get nodes && \
             echo 'Successfully connected to OKE cluster via bastion'"
