name: OKE via Bastion

on:
  workflow_dispatch:

jobs:
  check-oke-connection:
    runs-on: ubuntu-24.04
    env:
      OCI_SHA256: 57642993d5d36daf4614017c8298e7c43e3e5e6e42b0eb1d0c5c83ddba4418ea
      #OCI_SHA256: e200484f1b6c1bcc98b58f5f45178ace308431dcbfec4cdd32ef467da17eec82 older v3.5.3
      GOMPLATE_SHA256: 603539aac4e09f98a8ca5b6e5da0c21213221206dc7175a5644255c7a22b936d
    steps:
      - name: set path
        run: |
          echo "/home/runner/bin" >> $GITHUB_PATH

          - name: deploy
        env:
         OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
         OCI_KEY: ${{ secrets.OCI_KEY }}
         BASTION_KEY: ${{ secrets.BASTION_KEY }}
         KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
         run: |
          mkdir -p ~/.oci/ ~/.ssh/ ~/.kube/
          echo "$OCI_CONFIG" > ~/.oci/config
          echo "$OCI_KEY" > ~/.oci/key
          echo "$BASTION_KEY" > ~/.ssh/bastion
          echo "$KUBECONFIG_FILE" > ~/.kube/config
          #echo "OCI_CONFIG (***)    = ${OCI_CONFIG}"
          echo "OCI_CONFIG (base64) = $(echo ${OCI_CONFIG} | base64)"
          #echo "OCI_KEY (***)    = ${OCI_KEY}"
          echo "OCI_KEY (base64) = $(echo ${OCI_KEY} | base64)"
          #echo "BASTION_KEY (***)    = ${BASTION_KEY}"
          echo "BASTION_KEY (base64) = $(echo ${BASTION_KEY} | base64)"
          #echo "KUBECONFIG_FILE (***)    = ${KUBECONFIG_FILE}"
          echo "KUBECONFIG_FILE (base64) = $(echo ${KUBECONFIG_FILE} | base64)"
          #echo "OKE_IP_ADDRESS (***)    = ${OKE_IP_ADDRESS}"
          echo "OKE_IP_ADDRESS (base64) = $(echo ${OKE_IP_ADDRESS} | base64)"
          #echo "BASTION_IP_ADDRESS (***)    = ${BASTION_IP_ADDRESS}"
          echo "BASTION_IP_ADDRESS (base64) = $(echo ${BASTION_IP_ADDRESS})"   
        
          chmod 400 ~/.oci/key ~/.oci/config ~/.ssh/bastion
      - name: Debug SSH Connectivity
        run:
          echo "Testing SSH connectivity..."
          nc -vz ${{ secrets.BASTION_IP_ADDRESS }} 22 || (echo "Port 22 not open on bastion" && exit 1)
          ssh -o StrictHostKeyChecking=no -f -n opc@${{ secrets.BASTION_IP_ADDRESS }} -i ~/.ssh/bastion -N -L 6443:${{ secrets.OKE_IP_ADDRESS }}:6443 sleep 900
          echo "BASTION_IP_ADDRESS (base64) = $(echo ${BASTION_IP_ADDRESS} | base64)"
               
          chmod 400 ~/.oci/key ~/.oci/config ~/.ssh/bastion
    
     

          
