name: Test OKE_4 Connectivity

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-oke-connection:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create OCI API key file
        run: |
         mkdir -p ~/.oci
         echo "${{ secrets.OCI_API_KEY }}" > ~/.oci/oci_api_key
         chmod 600 ~/.oci/oci_api_key
#  Install kubeseal if was not found in cache
      - name: install kubeseal, kubeval, gomplate, kube-score, oci
        if: steps.kubeseal-kubeval-gomplate-kubescore-oci-cache.outputs.cache-hit != 'true'
        working-directory: .github/workflows
        env:
          ENV_INSTALL_KUBESEAL: true
          ENV_INSTALL_KUBEVAL: true
          ENV_INSTALL_GOMPLATE: true
          ENV_INSTALL_KUBESCORE: true
          ENV_INSTALL_OCI: true
        run: |
          ./install-dependencies.sh

      - name: Lint k8s, kubescore tests, kubeval tests, Yaml validations on PR
        run: |
          ENV_VALIDATE_SEALED_SECRETS_ENABLED=false ENV_VALIDATE_YAML_FILE_REFERENCES_IN_KUSTOMIZATION=true ./.github/workflows/lint-k8s-manifests.sh        

      - name: k8s secrets validation non prod
        env:
          BASTION_KEY: ${{ secrets.BASTION_KEY }}
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_KEY: ${{ secrets.OCI_KEY }}
          BASTION_IP_ADDRESS: ${{ secrets.BASTION_IP_ADDRESS }}
          OKE_IP_ADDRESS: ${{ secrets.OKE_IP_ADDRESS }}
        run: |
          ## Installation of binaries, set up .ssh and .kube dir
          mkdir -p ~/.oci/ ~/.ssh/ ~/.kube/
          echo "$OCI_CONFIG" > ~/.oci/config
          echo "$OCI_KEY" > ~/.oci/key
          echo "$BASTION_KEY" > ~/.ssh/bastion
          echo "$KUBECONFIG_FILE" > ~/.kube/config
          chmod 400 ~/.oci/key ~/.oci/config ~/.ssh/bastion
          ssh -o LogLevel=ERROR -o StrictHostKeyChecking=no -f -n opc@${{ secrets.BASTION_IP_ADDRESS }} -i ~/.ssh/bastion -N -L 6443:${{ secrets.OKE_IP_ADDRESS }}:6443 sleep 900
          ENV_ENABLE_BUILD_TEST=false ENV_VALIDATE_SEALED_SECRETS_ENABLED=true ./.github/workflows/lint-k8s-manifests.sh
